# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments')),
                ('isencrypted', models.BooleanField(default=False)),
                ('hash', models.CharField(blank=True, max_length=40, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('report_name', models.CharField(max_length=50, unique=True)),
                ('company_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('company_location', models.CharField(max_length=20)),
                ('company_country', models.CharField(max_length=20)),
                ('sector', models.CharField(choices=[('GenTech', 'General Technology'), ('HthTech', 'Health Technology'), ('SpcTech', 'Space Technology'), ('AITech', 'Artificial Intelligence Technology'), ('RobTech', 'Robot Technology')], max_length=7)),
                ('industry', models.CharField(choices=[('Tech', 'Technology'), ('ArHu', 'Arts and Humanities')], max_length=4)),
                ('current_projects', models.CharField(max_length=500)),
                ('isprivate', models.BooleanField(default=True)),
                ('hash', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('groups', models.ManyToManyField(to='auth.Group')),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReportCreater.Report'),
        ),
    ]
