# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportCreater', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='isencrypted',
        ),
        migrations.AddField(
            model_name='attachment',
            name='seqid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='isencrypted',
            field=models.BooleanField(default=False),
        ),
    ]
